#include "constants.h"
#include "interface.h"
                  
                  
/* code des compétence en langage des signes et en codage LPC */
                  
/* competences des interfaces en SIGNES et CODAGE*/
int competences_interfaces[NBR_INTERFACES][2]={
    {1,0}, /* compétence en langages des SIGNES mais pas en CODAGE LPC */
    {0,1}, /* pas de compétence en langages des SIGNES mais compétence en CODAGE LPC */
    {0,1},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {1,0},
    {0,1},
    {1,1},
    {1,0},
    {1,0},
    {0,1},
    {1,0},
    {0,1},
    {0,1},
    {1,0},
    {1,1},
    {1,0},
    {0,1}
};
                  
/* spécialités des interfaces */
                  
/* specialite des interfaces */
int specialite_interfaces[NBR_INTERFACES][NBR_SPECIALITES]={
    {0,0,0,0,0},
    {0,0,0,0,0},
    {1,0,0,0,0},
    {0,1,0,1,0},
    {0,0,0,0,0},
    {1,0,1,0,0},
    {1,0,1,0,0},
    {0,0,1,0,0},
    {0,1,1,0,0},
    {0,0,0,0,0},
    {0,0,0,0,1},
    {0,0,0,0,0},
    {0,0,0,1,1},
    {1,0,0,0,0},
    {0,0,1,0,0},
    {0,1,0,0,1},
    {0,1,0,0,0},
    {1,1,0,1,1},
    {0,1,0,0,0},
    {1,0,0,0,1},
    {1,0,0,1,1},
    {0,0,0,0,0},
    {0,0,1,0,0},
    {0,0,0,0,0}
};
                  
/* coordonnées des centres de formation, des interfaces et des apprenants */
float coord[NBR_NODES][2]={
                  
    /* Les interfaces se rendent du centre SESSAD à l'école de formation */
    {190,171}, /* centre 0 */
                  
    /* Centres de formation */
    {37,10}, /* ecole formation SPECIALITE_MENUISERIE */
    {121,66}, /* ecole formation SPECIALITE_ELECTRICITE */
    {167,143}, /* ecole formation SPECIALITE_MECANIQUE */
    {20,86}, /* ecole formation SPECIALITE_INFORMATIQUE */
    {36,26}, /* ecole formation SPECIALITE_CUISINE */
                  
    /* Apprenants */

};
                  
                  
                  
/* formation : id formation, specialite ou centre de formation, competence, horaire debut formation, horaire fin formation */
int formation[NBR_FORMATIONS][6]={
   {0,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,8,10},
   {1,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,SAMEDI,10,12},
   {2,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,13,17},
   {3,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,8,10},
   {4,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,10,12},
   {5,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,9,11},
   {6,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,9,12},
   {7,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,8,12},
   {8,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,9,12},
   {9,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,9,12},
   {10,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,14,19},
   {11,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,LUNDI,9,11},
   {12,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,9,11},
   {13,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,13,19},
   {14,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {15,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,16,18},
   {16,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,9,12},
   {17,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,15,17},
   {18,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,JEUDI,10,12},
   {19,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,10,12},
   {20,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,8,12},
   {21,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,SAMEDI,9,12},
   {22,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,16,19},
   {23,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,14,16},
   {24,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,10,12},
   {25,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,9,11},
   {26,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,9,12},
   {27,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,8,11},
   {28,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,8,12},
   {29,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,14,16},
   {30,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,9,12},
   {31,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,9,12},
   {32,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,SAMEDI,9,12},
   {33,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,8,12},
   {34,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,14,16},
   {35,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,VENDREDI,16,19},
   {36,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MARDI,16,18},
   {37,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,VENDREDI,14,19},
   {38,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,13,18},
   {39,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,9,11},
   {40,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,9,12},
   {41,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,9,12},
   {42,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MARDI,15,18},
   {43,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,13,16},
   {44,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,LUNDI,9,11},
   {45,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,13,15},
   {46,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,13,15},
   {47,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MARDI,9,12},
   {48,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,8,10},
   {49,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,13,15},
   {50,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,16,19},
   {51,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,13,16},
   {52,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,14,16},
   {53,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,16,19},
   {54,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,9,12},
   {55,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,16,19},
   {56,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,16,19},
   {57,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {58,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,10,12},
   {59,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,15,17},
   {60,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,16,19},
   {61,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,13,19},
   {62,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,10,12},
   {63,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,10,12},
   {64,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,13,18},
   {65,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,16,18},
   {66,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,10,12},
   {67,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,13,17},
   {68,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,13,15},
   {69,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,8,10},
   {70,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,14,16},
   {71,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,10,12},
   {72,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,13,17},
   {73,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,8,11},
   {74,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,SAMEDI,9,12},
   {75,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,10,12},
   {76,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,15,18},
   {77,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,9,11},
   {78,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,9,12},
   {79,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,14,16}
};
                  
//Variables globales utilisees dans le reste du programme
double distances[NBR_SPECIALITES + 1][NBR_SPECIALITES + 1];
Interface infos_interface[NBR_INTERFACES];
