#include "constants.h"
#include "interface.h"
                  
                  
/* code des compétence en langage des signes et en codage LPC */
                  
/* competences des interfaces en SIGNES et CODAGE*/
int competences_interfaces[NBR_INTERFACES][2]={
    {1,0}, /* compétence en langages des SIGNES mais pas en CODAGE LPC */
    {0,1}, /* pas de compétence en langages des SIGNES mais compétence en CODAGE LPC */
    {0,1},
    {1,0},
    {0,1},
    {1,0},
    {1,0},
    {0,1},
    {0,1},
    {1,0},
    {0,1},
    {1,0},
    {0,1},
    {0,1},
    {1,0},
    {0,1},
    {1,0},
    {1,0},
    {0,1},
    {1,0},
    {1,0},
    {1,1},
    {1,0},
    {0,1}
};
                  
/* spécialités des interfaces */
                  
/* specialite des interfaces */
int specialite_interfaces[NBR_INTERFACES][NBR_SPECIALITES]={
    {0,1,1,0,0},
    {0,0,1,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,1,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,0,1,0},
    {0,1,1,0,0},
    {1,0,1,0,1},
    {0,0,1,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {1,0,0,0,0},
    {0,0,1,0,0},
    {0,1,1,0,0},
    {0,0,0,1,0},
    {0,0,0,0,0},
    {0,0,0,1,0},
    {0,0,0,0,1},
    {0,0,0,0,1},
    {0,0,0,0,1}
};
                  
/* coordonnées des centres de formation, des interfaces et des apprenants */
float coord[NBR_NODES][2]={
                  
    /* Les interfaces se rendent du centre SESSAD à l'école de formation */
    {196,70}, /* centre 0 */
                  
    /* Centres de formation */
    {72,171}, /* ecole formation SPECIALITE_MENUISERIE */
    {44,123}, /* ecole formation SPECIALITE_ELECTRICITE */
    {67,82}, /* ecole formation SPECIALITE_MECANIQUE */
    {54,140}, /* ecole formation SPECIALITE_INFORMATIQUE */
    {67,151}, /* ecole formation SPECIALITE_CUISINE */
                  
    /* Apprenants */

};
                  
                  
                  
/* formation : id formation, specialite ou centre de formation, competence, horaire debut formation, horaire fin formation */
int formation[NBR_FORMATIONS][6]={
   {0,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,10,12},
   {1,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,10,12},
   {2,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,8,10},
   {3,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,SAMEDI,10,12},
   {4,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MARDI,9,11},
   {5,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,13,17},
   {6,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,8,10},
   {7,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,9,11},
   {8,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,14,18},
   {9,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,8,11},
   {10,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,13,15},
   {11,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,10,12},
   {12,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,9,12},
   {13,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,SAMEDI,8,10},
   {14,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,14,16},
   {15,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {16,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,9,12},
   {17,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,10,12},
   {18,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,JEUDI,13,19},
   {19,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,13,18},
   {20,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,14,17},
   {21,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,9,12},
   {22,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,9,12},
   {23,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,16,19},
   {24,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,16,19},
   {25,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,15,18},
   {26,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,14,19},
   {27,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,15,18},
   {28,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MERCREDI,13,18},
   {29,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,10,12},
   {30,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,15,17},
   {31,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,SAMEDI,9,12},
   {32,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,13,18},
   {33,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,14,16},
   {34,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,JEUDI,9,11},
   {35,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,8,10},
   {36,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,14,16},
   {37,SPECIALITE_CUISINE,COMPETENCE_CODAGE,SAMEDI,16,18},
   {38,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,16,18},
   {39,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,8,11},
   {40,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,15,18},
   {41,SPECIALITE_CUISINE,COMPETENCE_SIGNES,LUNDI,15,18},
   {42,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,LUNDI,8,10},
   {43,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,8,11},
   {44,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,10,12},
   {45,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,14,17},
   {46,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,8,11},
   {47,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,8,10},
   {48,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,14,17},
   {49,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,10,12},
   {50,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,9,11},
   {51,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,13,15},
   {52,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,8,10},
   {53,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,VENDREDI,13,18},
   {54,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,14,17},
   {55,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,10,12},
   {56,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,15,19},
   {57,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,8,10},
   {58,SPECIALITE_CUISINE,COMPETENCE_SIGNES,VENDREDI,9,12},
   {59,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,13,18},
   {60,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,9,12},
   {61,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,14,19},
   {62,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MARDI,8,10},
   {63,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,15,19},
   {64,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,10,12},
   {65,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,10,12},
   {66,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,10,12},
   {67,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,15,17},
   {68,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,LUNDI,13,15},
   {69,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,8,11},
   {70,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,16,19},
   {71,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,15,19},
   {72,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,13,15},
   {73,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,9,11},
   {74,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,16,18},
   {75,SPECIALITE_CUISINE,COMPETENCE_CODAGE,JEUDI,16,18},
   {76,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,8,12},
   {77,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,10,12},
   {78,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,16,18},
   {79,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,10,12}
};
                  
//Variables globales utilisees dans le reste du programme
double distances[NBR_SPECIALITES + 1][NBR_SPECIALITES + 1];
